// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'package:dante/models/goal.dart' as prefix1;
import 'package:dante/models/model.dart' as prefix0;
import 'package:json_annotation/src/json_serializable.dart' as prefix2;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_builder_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Model(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"Goal",
            r".Goal",
            7,
            0,
            const prefix0.Model(),
            const <int>[0, 1, 2, 3, 4, 5, 16, 17],
            const <int>[
              18,
              19,
              20,
              21,
              22,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15
            ],
            const <int>[],
            -1,
            {},
            {},
            {
              r"": (b) => ({id, date, title, aspect, howToMesure}) => b
                  ? new prefix1.Goal(
                      id: id,
                      date: date,
                      title: title,
                      aspect: aspect,
                      howToMesure: howToMesure)
                  : null,
              r"fromJson": (b) =>
                  (json) => b ? new prefix1.Goal.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              const prefix0.Model(),
              const prefix2.JsonSerializable()
            ],
            null)
      ],
      <m.DeclarationMirror>[
        new r.VariableMirrorImpl(r"id", 32773, 0, const prefix0.Model(), -1, -1,
            -1, null, const <Object>[const prefix0.PrimaryKey()]),
        new r.VariableMirrorImpl(r"date", 32773, 0, const prefix0.Model(), -1,
            -1, -1, null, const <Object>[]),
        new r.VariableMirrorImpl(r"title", 32773, 0, const prefix0.Model(), -1,
            -1, -1, null, const <Object>[]),
        new r.VariableMirrorImpl(r"aspect", 32773, 0, const prefix0.Model(), -1,
            -1, -1, null, const <Object>[]),
        new r.VariableMirrorImpl(r"howToMesure", 32773, 0,
            const prefix0.Model(), -1, -1, -1, null, const <Object>[]),
        new r.MethodMirrorImpl(r"toJson", 4325378, 0, -1, -1, -1, null,
            const <int>[], const prefix0.Model(), const <Object>[]),
        new r.ImplicitGetterMirrorImpl(const prefix0.Model(), 0, -1, -1, 6),
        new r.ImplicitSetterMirrorImpl(const prefix0.Model(), 0, -1, -1, 7),
        new r.ImplicitGetterMirrorImpl(const prefix0.Model(), 1, -1, -1, 8),
        new r.ImplicitSetterMirrorImpl(const prefix0.Model(), 1, -1, -1, 9),
        new r.ImplicitGetterMirrorImpl(const prefix0.Model(), 2, -1, -1, 10),
        new r.ImplicitSetterMirrorImpl(const prefix0.Model(), 2, -1, -1, 11),
        new r.ImplicitGetterMirrorImpl(const prefix0.Model(), 3, -1, -1, 12),
        new r.ImplicitSetterMirrorImpl(const prefix0.Model(), 3, -1, -1, 13),
        new r.ImplicitGetterMirrorImpl(const prefix0.Model(), 4, -1, -1, 14),
        new r.ImplicitSetterMirrorImpl(const prefix0.Model(), 4, -1, -1, 15),
        new r.MethodMirrorImpl(
            r"",
            0,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[0, 1, 2, 3, 4],
            const prefix0.Model(),
            const <Object>[]),
        new r.MethodMirrorImpl(r"fromJson", 1, 0, -1, -1, -1, null,
            const <int>[5], const prefix0.Model(), const <Object>[]),
        new r.MethodMirrorImpl(r"==", 131074, null, -1, -1, -1, null,
            const <int>[11], const prefix0.Model(), const <Object>[]),
        new r.MethodMirrorImpl(r"toString", 131074, null, -1, -1, -1, null,
            const <int>[], const prefix0.Model(), const <Object>[]),
        new r.MethodMirrorImpl(
            r"noSuchMethod",
            65538,
            null,
            null,
            -1,
            -1,
            null,
            const <int>[12],
            const prefix0.Model(),
            const <Object>[const pragma("vm:entry-point")]),
        new r.MethodMirrorImpl(r"hashCode", 131075, null, -1, -1, -1, null,
            const <int>[], const prefix0.Model(), const <Object>[]),
        new r.MethodMirrorImpl(r"runtimeType", 131075, null, -1, -1, -1, null,
            const <int>[], const prefix0.Model(), const <Object>[])
      ],
      <m.ParameterMirror>[
        new r.ParameterMirrorImpl(r"id", 45062, 16, const prefix0.Model(), -1,
            -1, -1, null, const <Object>[], null, #id),
        new r.ParameterMirrorImpl(r"date", 47110, 16, const prefix0.Model(), -1,
            -1, -1, null, const <Object>[], null, #date),
        new r.ParameterMirrorImpl(r"title", 47110, 16, const prefix0.Model(),
            -1, -1, -1, null, const <Object>[], null, #title),
        new r.ParameterMirrorImpl(r"aspect", 47110, 16, const prefix0.Model(),
            -1, -1, -1, null, const <Object>[], null, #aspect),
        new r.ParameterMirrorImpl(
            r"howToMesure",
            47110,
            16,
            const prefix0.Model(),
            -1,
            -1,
            -1,
            null,
            const <Object>[],
            null,
            #howToMesure),
        new r.ParameterMirrorImpl(r"json", 2129926, 17, const prefix0.Model(),
            -1, -1, -1, null, const <Object>[], null, null),
        new r.ParameterMirrorImpl(r"_id", 32870, 7, const prefix0.Model(), -1,
            -1, -1, null, const [], null, null),
        new r.ParameterMirrorImpl(r"_date", 32870, 9, const prefix0.Model(), -1,
            -1, -1, null, const [], null, null),
        new r.ParameterMirrorImpl(r"_title", 32870, 11, const prefix0.Model(),
            -1, -1, -1, null, const [], null, null),
        new r.ParameterMirrorImpl(r"_aspect", 32870, 13, const prefix0.Model(),
            -1, -1, -1, null, const [], null, null),
        new r.ParameterMirrorImpl(r"_howToMesure", 32870, 15,
            const prefix0.Model(), -1, -1, -1, null, const [], null, null),
        new r.ParameterMirrorImpl(r"other", 16390, 18, const prefix0.Model(),
            null, -1, -1, null, const <Object>[], null, null),
        new r.ParameterMirrorImpl(
            r"invocation",
            32774,
            20,
            const prefix0.Model(),
            -1,
            -1,
            -1,
            null,
            const <Object>[],
            null,
            null)
      ],
      <Type>[prefix1.Goal],
      1,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"toJson": (dynamic instance) => instance.toJson,
        r"id": (dynamic instance) => instance.id,
        r"date": (dynamic instance) => instance.date,
        r"title": (dynamic instance) => instance.title,
        r"aspect": (dynamic instance) => instance.aspect,
        r"howToMesure": (dynamic instance) => instance.howToMesure
      },
      {
        r"id=": (dynamic instance, value) => instance.id = value,
        r"date=": (dynamic instance, value) => instance.date = value,
        r"title=": (dynamic instance, value) => instance.title = value,
        r"aspect=": (dynamic instance, value) => instance.aspect = value,
        r"howToMesure=": (dynamic instance, value) =>
            instance.howToMesure = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
